site_name: Eblasoft Documentation

repo_url: https://github.com/eblasoft/documentation/

markdown_extensions:
  #  - mdx_truly_sane_lists
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
      toc_depth: 4

#theme:
#  name: material
#  highlightjs: true
#  palette:
#    primary: blue grey
#    accent: blue grey

nav:
  - 'Home': 'index.md'
  - 'Extensions':
      - 'Ebla Chat': 'extensions/ebla-chat/setting-up.md'
      - 'Ebla Enum Color': 'extensions/ebla-enum-color/setting-up.md'
      - 'Ebla IFrame': 'extensions/ebla-iframe/setting-up.md'
      - 'Ebla Switch': 'extensions/ebla-switch/setting-up.md'
      - 'Ebla Link Multiple Pro': 'extensions/ebla-link-multiple-pro/setting-up.md'
      - 'Ebla Nav Pro': 'extensions/ebla-nav-pro/setting-up.md'
      - 'Ebla Navbar User Quick Switch  Button': 'extensions/ebla-navbar-user-quick-switch-button/setting-up.md'
      - 'Ebla Rate': 'extensions/ebla-rate/setting-up.md'
      - 'Ebla Theme': 'extensions/ebla-theme/setting-up.md'
      - 'Ebla Varchar Plus': 'extensions/ebla-varchar-plus/setting-up.md'

        #      - 'Advanced Pack':
#  - 'Extensions':
#      - 'Ebla Chat': 'extensions/ebla-chat/setting-up.md'
#      - 'Ebla Enum Color':
#          - 'Colo Picker Field': 'extensions/ebla-enum-color/color-picker-field/color-picker-field.md'
#          - 'Enum Type': 'extensions/ebla-enum-color/enum-type/enum-type.md'
#      - 'Ebla IFrame':
#          - 'Display Mode':
#              - 'Inline IFrame': 'extensions/ebla-iframe/iframe/display-mode/inline-iframe.md'
#              - 'Button And Modal': 'extensions/ebla-iframe/iframe/display-mode/button-and-modal.md'
#              - 'Button And Popup Window': 'extensions/ebla-iframe/iframe/display-mode/button-and-popup-window.md'
#      - 'Ebla Link Multiple Pro':
#          - 'Footer Sum': 'extensions/ebla-link-multiple-pro/footer-sum/footer-sum.md'
#          - 'Layout':
#              - 'Custom Layout': 'extensions/ebla-link-multiple-pro/layout/custom-layout.md'
#              - 'List Layout': 'extensions/ebla-link-multiple-pro/layout/list-layout.md'
#              - 'List Small Layout': 'extensions/ebla-link-multiple-pro/layout/list-small-layout.md'
#          - 'Row Action Items':
#              - 'Edit': 'extensions/ebla-link-multiple-pro/row-action-items/edit.md'
#              - 'Remove': 'extensions/ebla-link-multiple-pro/row-action-items/remove.md'
#              - 'View': 'extensions/ebla-link-multiple-pro/row-action-items/view.md'
#              - 'Unlink': 'extensions/ebla-link-multiple-pro/row-action-items/unlink.md'
#          - 'Select Buttons':
#              - 'Add Button': 'extensions/ebla-link-multiple-pro/select-buttons/add-button.md'
#              - 'Select Button': 'extensions/ebla-link-multiple-pro/select-buttons/select-button.md'
#      - 'Ebla Nav Pro':
#          - 'Custom Link': 'extensions/ebla-nav-pro/custom-link/custom-link.md'
#          - 'Favorite Entity': 'extensions/ebla-nav-pro/favorite-entity/favorite-entity.md'
#          - 'Separator': 'extensions/ebla-nav-pro/separator/separator.md'
#      -  'Ebla Navbar User Quick Switch  Button':
#             - 'Nav Bar user Switch Button': 'extensions/ebla-navbar-user-quick-switch-button/nav-bar-user-switch-button/nav-bar-user-switch-button.md'
#             - 'Top Nav Work Log Button': 'extensions/ebla-navbar-user-quick-switch-button/top-nav-work-log-button/top-nav-work-log-button.md'
#
#      - 'Ebla Rate' : 'extensions/ebla-rate/setting-up.md'
#      - 'Ebla Theme':
#            - 'Color Customization': 'extensions/ebla-theme/color-customization/color-customization.md'
#            - 'Favicon': 'extensions/ebla-theme/favicon/favicon.md'
#            - 'Login Background Image': 'extensions/ebla-theme/login-background-image/login-background-image.md'
#            - 'Side Menu': 'extensions/ebla-theme/side-menu/side-menu.md'
#      - 'Ebla Varchar Plus':
#            - 'Auto Complete': 'extensions/ebla-varchar-plus/auto-complete/auto-complete.md'
#            - 'Is Unique': 'extensions/ebla-varchar-plus/is-unique/is-unique.md'
#            - 'Prefix Label': 'extensions/ebla-varchar-plus/prefix-label/prefix-label.md'
#            - 'Suffix Label': 'extensions/ebla-varchar-plus/suffix-label/suffix-label.md'
 #      - 'Advanced Pack':
#          - 'Reports': 'user-guide/reports.md'
#          - 'Workflows': 'administration/workflows.md'
#          - 'BPM':
#              - 'Overview': 'administration/bpm.md'
#              - 'Events': 'administration/bpm-events.md'
#              - 'Gateways': 'administration/bpm-gateways.md'
#              - 'Activities': 'administration/bpm-activities.md'
#              - 'Misc':
#                  - 'Examples': 'administration/bpm-examples.md'
#                  - 'Signals': 'administration/bpm-signals.md'
#                  - 'Formula functions': 'administration/bpm-formula.md'
#                  - 'Drip email campaign': 'administration/bpm-drip-email-campaign.md'
#                  - 'Tracking URLs': 'administration/bpm-tracking-urls.md'
#                  - 'Tips': 'administration/bpm-tips.md'
#                  - 'Configuration': 'administration/bpm-configuration.md'
#      - 'Sales Pack':
#          - 'Products': 'user-guide/products.md'
#          - 'Quotes': 'user-guide/quotes.md'
#          - 'Sales Orders': 'user-guide/sales-orders.md'
#          - 'Invoices': 'user-guide/invoices.md'
#      - 'Google Integration':
#          - 'Setting-up': 'extensions/google-integration/setting-up.md'
#          - 'Calendar': 'extensions/google-integration/calendar.md'
#          - 'Contacts': 'extensions/google-integration/contacts.md'
#          - 'Gmail': 'extensions/google-integration/gmail.md'
#      - 'Outlook Integration':
#          - 'Setting-up': 'extensions/outlook-integration/setting-up.md'
#          - 'Calendar': 'extensions/outlook-integration/calendar.md'
#          - 'Contacts': 'extensions/outlook-integration/contacts.md'
#          - 'Email': 'extensions/outlook-integration/email.md'
#      - 'VoIP Integration':
#          - 'Asterisk server': 'extensions/voip-integration/asterisk-integration-setup.md'
#          - 'Binotel service' : 'extensions/voip-integration/binotel-integration-setup.md'
#          - 'Starface server': 'extensions/voip-integration/starface-integration-setup.md'
#          - 'Twilio service' : 'extensions/voip-integration/twilio-integration-setup.md'
#          - 'IexPBX server' : 'extensions/voip-integration/iexpbx-integration-setup.md'
#          - 'Docker container': 'extensions/voip-integration/docker-container.md'
#          - 'Customization': 'extensions/voip-integration/customization.md'
#          - 'Troubleshooting' : 'extensions/voip-integration/troubleshooting.md'
#  - 'Developer':
#      - 'Index': 'development/index.md'
#      - 'Getting started': 'development/how-to-start.md'
#      - 'Making extension package': 'development/extension-packages.md'
#      - 'Modules': 'development/modules.md'
#      - 'Tests': 'development/tests.md'
#      - 'Translation': 'development/translation.md'
#      - 'Coding rules': 'development/coding-rules.md'
#      - 'Backend':
#          - 'API': 'development/api.md'
#          - 'Dependency injection': 'development/di.md'
#          - 'Metadata': 'development/metadata.md'
#          - 'Metadata reference':
#              - 'scopes': 'development/metadata/scopes.md'
#              - 'entityDefs': 'development/metadata/entity-defs.md'
#              - 'aclDefs': 'development/metadata/acl-defs.md'
#              - 'selectDefs': 'development/metadata/select-defs.md'
#              - 'recordDefs': 'development/metadata/record-defs.md'
#              - 'clientDefs': 'development/metadata/client-defs.md'
#              - 'entityAcl': 'development/metadata/entity-acl.md'
#              - 'pdfDefs': 'development/metadata/pdf-defs.md'
#              - 'notificationDefs': 'development/metadata/notification-defs.md'
#              - 'streamDefs': 'development/metadata/stream-defs.md'
#              - 'fields': 'development/metadata/fields.md'
#              - 'dashlets': 'development/metadata/dashlets.md'
#              - 'authenticationMethods': 'development/metadata/authentication-methods.md'
#              - 'integrations': 'development/metadata/integrations.md'
#              - 'app':
#                  - 'acl': 'development/metadata/app-acl.md'
#                  - 'acl-portal': 'development/metadata/app-acl-portal.md'
#                  - 'actions': 'development/metadata/app-actions.md'
#                  - 'address-formats': 'development/metadata/app-address-formats.md'
#                  - 'admin-panel': 'development/metadata/app-admin-panel.md'
#                  - 'api': 'development/metadata/app-api.md'
#                  - 'app-params': 'development/metadata/app-app-params.md'
#                  - 'authentication': 'development/metadata/app-authentication.md'
#                  - 'authentication2FAMethods': 'development/metadata/app-authentication-2fa-methods.md'
#                  - 'cleanup': 'development/metadata/app-cleanup.md'
#                  - 'client': 'development/metadata/app-client.md'
#                  - 'clientRoutes': 'development/metadata/app-client-routes.md'
#                  - 'complexExpression': 'development/metadata/app-complex-expression.md'
#                  - 'config': 'development/metadata/app-config.md'
#                  - 'consoleCommands': 'development/metadata/app-console-commands.md'
#                  - 'containerServices': 'development/metadata/app-container-services.md'
#                  - 'currency': 'development/metadata/app-currency.md'
#                  - 'database': 'development/metadata/app-database.md'
#                  - 'dateTime': 'development/metadata/app-date-time.md'
#                  - 'defaultDashboardLayouts': 'development/metadata/app-default-dashboard-layouts.md'
#                  - 'defaultDashboardOptions': 'development/metadata/app-default-dashboard-options.md'
#                  - 'entityTemplateList': 'development/metadata/app-entity-template-list.md'
#                  - 'export': 'development/metadata/app-export.md'
#                  - 'fieldProcessing': 'development/metadata/app-field-processing.md'
#                  - 'file': 'development/metadata/app-file.md'
#                  - 'fileStorage': 'development/metadata/app-file-storage.md'
#                  - 'formula': 'development/metadata/app-formula.md'
#                  - 'hook': 'development/metadata/app-hook.md'
#                  - 'image': 'development/metadata/app-image.md'
#                  - 'jsLibs': 'development/metadata/app-js-libs.md'
#                  - 'language': 'development/metadata/app-language.md'
#                  - 'linkManager': 'development/metadata/app-link-manager.md'
#                  - 'massActions': 'development/metadata/app-mass-actions.md'
#                  - 'metadata': 'development/metadata/app-metadata.md'
#                  - 'orm': 'development/metadata/app-orm.md'
#                  - 'pdfEngines': 'development/metadata/app-pdf-engines.md'
#                  - 'popupNotifications': 'development/metadata/app-popup-notifications.md'
#                  - 'portalContainerServices': 'development/metadata/app-portal-container-services.md'
#                  - 'rebuild': 'development/metadata/app-rebuild.md'
#                  - 'regExpPatterns': 'development/metadata/app-reg-exp-patterns.md'
#                  - 'scheduledJobs': 'development/metadata/app-scheduled-jobs.md'
#                  - 'smsProviders': 'development/metadata/app-sms-prividers.md'
#                  - 'templateHelpers': 'development/metadata/app-template-helpers.md'
#                  - 'templates': 'development/metadata/app-templates.md'
#                  - 'webSocket': 'development/metadata/app-web-socket.md'
#          - 'ORM': 'development/orm.md'
#          - 'Select Builder': 'development/select-builder.md'
#          - 'API actions': 'development/api-action.md'
#          - 'Services': 'development/services.md'
#          - 'Hooks': 'development/hooks.md'
#          - 'ACL': 'development/acl.md'
#          - 'Misc':
#              - 'Template (PDF) custom helpers': 'development/template-custom-helper.md'
#              - 'Custom functions for formula': 'development/new-function-in-formula.md'
#              - 'Custom scheduled jobs': 'development/scheduled-job.md'
#              - 'Duplicate checking': 'development/duplicate-check.md'
#              - 'Database indexes': 'development/db-indexes.md'
#              - 'App params': 'development/app-params.md'
#              - 'Jobs': 'development/jobs.md'
#              - 'Email sending': 'development/email-sending.md'
#              - 'Calculated fields': 'development/calculated-fields.md'
#              - 'Custom config parameters': 'development/custom-config-parameters.md'
#      - 'Frontend':
#          - 'View': 'development/view.md'
#          - 'Custom views': 'development/custom-views.md'
#          - 'Templates': 'development/frontend/templates.md'
#          - 'Fields':
#              - 'Custom field type': 'development/custom-field-type.md'
#              - 'Customizing existing fields': 'development/customize-standard-fields.md'
#          - 'Controller & routing': 'development/frontend/controller.md'
#          - 'Model': 'development/model.md'
#          - 'Collection': 'development/collection.md'
#          - 'HTML & CSS': 'development/frontend/html-css.md'
#          - 'Ajax requests': 'development/frontend/ajax.md'
#          - 'Misc':
#              - 'Custom buttons & dropdown actions': 'development/custom-buttons.md'
#              - 'Modal dialogs': 'development/modal.md'
#              - 'Confirmation dialogs': 'development/confirm-dialog.md'
#              - 'Custom panels on record view': 'development/frontend/record-panels.md'
#              - 'Including custom CSS file': 'development/custom-css.md'
#              - 'Custom dashlets': 'development/how-to-create-a-dashlet.md'
#              - 'Dynamic forms with dynamic handler': 'development/dynamic-handler.md'
#              - 'Link-multiple field with primary record': 'development/link-multiple-with-primary.md'
#              - 'View setup handlers': 'development/frontend/view-setup-handlers.md'
#              - 'Save error handlers': 'development/frontend/save-error-handlers.md'
#              - 'Campaigns':
#                  -  'Custom unsubscribe page': 'development/campaign-unsubscribe-template.md'